import { RouteInfo } from "@core/interfaces/RouteInfo";

export const ROUTES: RouteInfo[] = [
  {
    path: "/pages/home",
    title: "Home",
    icon: "home-icon",
    groupTitle: false,
    role: ["All"],
    submenu: [],
    show: false,
  },
  {
    path: "/pages/service-providers",
    title: "Service Providers",
    icon: "service-provider-icon",
    groupTitle: false,
    role: ["All"],
    submenu: [],
    show: false,
  },
  {
    path: "/pages/gateways",
    title: "Gateways",
    icon: "gateways-icon",
    groupTitle: false,
    role: ["All"],
    submenu: [
      {
        path: "/pages/gateways/smpp",
        title: "SMPP / HTTP",
        icon: "gateway-icon",
        groupTitle: false,
        role: ["All"],
        submenu: [],
      },
      {
        path: "/pages/gateways/ss7",
        title: "SS7",
        icon: "gateway-icon",
        groupTitle: false,
        role: ["All"],
        submenu: [],
      },
    ],
    show: false,
  },
  {
    path: "/pages/rules-and-routing",
    title: "Rules and Routing",
    icon: "rules_and_Routing_icon",
    groupTitle: false,
    role: ["All"],
    submenu: [],
    show: false,
  },
  {
    path: "/pages/errors-management",
    title: "Error Management",
    icon: "response-code-icon",
    groupTitle: false,
    role: ["All"],
    submenu: [
      {
        path: "/pages/delivery-error-code",
        title: "Delivery Error Code",
        icon: "response-code-icon",
        groupTitle: false,
        role: ["All"],
        submenu: [],
      },
      {
        path: "/pages/error-code",
        title: "Error Code",
        icon: "response-code-icon",
        groupTitle: false,
        role: ["All"],
        submenu: [],
      },
      {
        path: "/pages/error-code-mappging",
        title: "Error Code Mapping",
        icon: "response-code-mapping-icon",
        groupTitle: false,
        role: ["All"],
        submenu: [],
      },
    ],
    show: false,
  },
  // {
  //   path: "/pages/reports",
  //   title: "Reports",
  //   icon: "reports",
  //   groupTitle: false,
  //   role: ["All"],
  //   submenu: [
  //     {
  //       path: "/pages/reports/general",
  //       title: "General",
  //       icon: "response-code-icon",
  //       groupTitle: false,
  //       role: ["All"],
  //       submenu: [],
  //     },
  //     {
  //       path: "/pages/reports/sms-report",
  //       title: "SMS",
  //       icon: "response-code-icon",
  //       groupTitle: false,
  //       role: ["All"],
  //       submenu: [],
  //     },
  //   ],
  //   show: false,
  // },
  {
    path: "/pages/settings",
    title: "Settings",
    icon: "settings-icon",
    groupTitle: false,
    role: ["All"],
    submenu: [
      {
        path: "/pages/settings",
        title: "General Settings",
        icon: "settings-icon",
        groupTitle: false,
        role: ["All"],
        submenu: [],
      },
      {
        path: "/pages/mnos",
        title: "MNOs",
        icon: "Mno-icon",
        groupTitle: false,
        role: ["All"],
        submenu: [],
      },
    ],
    show: false,
  },
];
