export interface SipGateways {
  network_id: number;
  ip_address: string;
  name: string;
  external_id?: string | null;
  status: string;
  protocol: string;
  port: number;
  transport: string;
  messages_per_second: number;
  messages_per_second_high: number;
  messages_per_second_medium: number;
  messages_per_second_low: number;
  transaction_timeout: number;
  retransmission_base_interval_ms: number;
  retransmission_max_interval_ms: number;
  network_timeout_ms: number;
  thread_pool_size: number;
  retransmission_filter: boolean;
  max_message_size: number;
  receive_udp_buffer_size: number;
  send_udp_buffer_size: number;
  aggressive_cleanup: boolean;
  routing_enable_ss7: boolean;
  routing_enable_diameter: boolean;
  routing_registration_traffic_ss7_gateway_id?: number | null;
  routing_registration_traffic_diameter_gateway_id?: number | null;
  routing_ussi_traffic_ss7_gateway_id?: number | null;
  auto_retry_error_code?: string | null;
  no_retry_error_code?: string | null;
  retry_alternate_destination_error_code?: string | null;
  enabled: number;
  register_max_expires?: number | null;
  ipsmgw_user?: string | null;
  ipsmgw_domain?: string | null;
  ims_domain?: string | null;
  ims_ccf?: string | null;
  ims_ecf?: string | null;
  subscribe_target_host?: string | null;
  subscribe_target_port?: number | null;
  subscribe_target_transport?: string | null;
  local_via_host?: string | null;
  mno_id: number | null;
  split_message: boolean;
}


export type SipGatewayFormValue = {
  network_id: number | null;
  ip_address: string;
  name: string;
  external_id: string | null;
  status: string;
  protocol: string;
  port: number | null;
  transport: string;
  messages_per_second: number | null;
  messages_per_second_high: number | null;
  messages_per_second_medium: number | null;
  messages_per_second_low: number | null;
  transaction_timeout: number | null;
  retransmission_base_interval_ms: number | null;
  retransmission_max_interval_ms: number | null;
  network_timeout_ms: number | null;
  thread_pool_size: number | null;
  retransmission_filter: boolean;
  max_message_size: number | null;
  receive_udp_buffer_size: number | null;
  send_udp_buffer_size: number | null;
  aggressive_cleanup: boolean;
  routing_enable_ss7: boolean;
  routing_enable_diameter: boolean;
  routing_registration_traffic_ss7_gateway_id: number | null;
  routing_registration_traffic_diameter_gateway_id: number | null;
  routing_ussi_traffic_ss7_gateway_id: number | null;
  auto_retry_error_code: string | null;
  no_retry_error_code: string | null;
  retry_alternate_destination_error_code: string | null;
  enabled: number;
  register_max_expires: number | null;
  ipsmgw_user: string | null;
  ipsmgw_domain: string | null;
  ims_domain: string | null;
  ims_ccf: string | null;
  ims_ecf: string | null;
  subscribe_target_host: string | null;
  subscribe_target_port: number | null;
  subscribe_target_transport: string | null;
  local_via_host: string | null;
  global_title: number | null;
  mno_id: number | null;
  ussi_default_datacoding_id: number | null;
  split_message: boolean;
};
